### ISSUE TITLE
Not able to download all targets within Device Database of Target Manager

### ISSUE THREAD

**Issue by ethanholda** [PTCInc/vuforia-engine#106] opened 2024-03-20 20:16 UTC
**Summarize the bug:**
"Download all" from Target Manager not working.

**Observed problem**
When I navigate to the Target Manager and select "download all", I get the modal to choose between "Android, XCode, Visual Studio" or "Unity". Regardless of which option I select, when I click the Download button, I get the spinner for a few seconds and then nothing happens, i.e., no download, and the Download button is then grayed out. The last time I had tryied to download was Nov 28, 2023 and I was able to do it successfully.

**Expected result**
I would normally get the zipped download in my download folder.

**Other observations**
I only have this issue with Download All. I am able to successfully download 1 page of objects at a time.

**Reproducible steps**
See above. This issue is reproducible on Safari and Chrome for Mac and Edge for Windows.

**Affected Vuforia Engine version:**
N/A

**Affected platform:**
N/A

**Affected device:**
N/A

**Screenshots / Video Recordings**
N/A

**Affected database**
Account number is 2028245 and database is `full_museum`

**Device or platform logs**
attached javascript logfiles from errors on download

[developer.vuforia.com-1710965577517.log](https://github.com/PTCInc/vuforia-engine/files/14672122/developer.vuforia.com-1710965577517.log)
[developer.vuforia.com-1710965602498.log](https://github.com/PTCInc/vuforia-engine/files/14672123/developer.vuforia.com-1710965602498.log)

**Workaround**
No

**Additional comments**
We use this in production for artwork identification in our mobile app and this is preventing us from adding any new trackable objects.

**Comment by ptc-pscheper** [comment] 2024-03-20 20:57
Hi there, I am not able to reproduce your issue but will check with our team as soon as possible. Can you verify that your affected database unique identifier (UUID) begins with `bd38d20b7`? This can be seen in the URL when opening your database in the browser. 

Also are other databases impacted on your account? Thank you.

**Comment by ptc-pscheper** [comment] 2024-03-20 20:58
And if you can download one target at a time, can you select multiple targets and try to download them? If so, can you try to select all in the list? There's an option (see screenshot) to show more targets per page. It could be that the issue is related to the size of the target database.

![image](https://github.com/PTCInc/vuforia-engine/assets/88328882/59fb93cc-cb10-46d3-a6c2-362c954f3a74)

**Comment by ethanholda** [comment] 2024-03-20 22:47
Hi Patrick. Yes, I can verify that `bd38d20b7` the identifier of the database. 

I can also download the max-per-page amount of targets (200).

When you say it may be related to the size of the database, do you mean it's number of objects or actual filesize (or both)? I was able to download the previous dataset in November and I've only added 1 object. I actually deleted an object earlier today and was still unable to download.

If this is related to size is there a way to verify? Is there a workaround?

**Comment by ptc-pscheper** [comment] 2024-03-21 09:12
Hi there, it could be related to both. Changes were made within the Target Manager which might have caused a regression. I have asked the team to investigate the issue. I will keep you updated!

**Comment by ptc-pscheper** [comment] 2024-03-21 14:24
Hi there, the team identified the issue and is working on a fix which will be released today. Thank you for your patience.

**Comment by ptc-pscheper** [comment] 2024-03-21 15:58
Hi, a fix has been deployed and you should be able to download your target database. Please let me know if the issue persists. For now the ticket has been closed.

**Closed by ptc-pscheper** 2024-03-21 15:58 UTC
Labels: bug-report

**Comment by ethanholda** [comment] 2024-03-21 16:30
Incredible! I can confirm that I can now download the trackable database.

Thanks so much. I deal with all sorts of vendor support for all kinds of different products and platforms and I'm honestly blown away by how responsive and effective you guys are.
