### ISSUE TITLE
can not upload PNG image to database of target manager

### ISSUE THREAD

**Issue by begkonfrank** [PTCInc/vuforia-engine#131] opened 2024-06-14 01:48 UTC
**Summarize the bug:**
I can not upload image to database of target manager

**Observed problem**
I was trying to add image to image target database. I can open the "add target" button and upload the image ,but when I click on the "add" button on the bottom, it will show the loading green circle icon for a second and then do nothing. 

the image is less than 2mb and the name is also correct, in a word the uploading process is correct , yet the website didn't respond.
I've tried microsoft edge and chrome but no use.
I've successfully uploaded images to the database before in april, but I don't understand why I can't upload now.  

**Expected result**
I can upload the image to the image target database

**Comment by ptc-thesbyro** [comment] 2024-06-14 07:19
Hi,

Could you verify that the image is either 8-bit or 24-bit per pixel?
* Must be 8- or 24-bit, PNG and JPG formats; less than 2 MB in size; JPGs must be RGB or greyscale. CMYK unsupported.

You can also share the image with us, and we can try to reproduce the issue. You may share it here or at vuforia-feedback@ptc.com. 

Thank you,

**Comment by begkonfrank** [comment] 2024-06-14 07:28
It's a simple QR code which contains the information: 001, btw I've tried with my colleague's computer with a different image, and it appear the same problem.
![002](https://github.com/PTCInc/vuforia-engine/assets/167400404/2751e989-e1fd-40ed-977d-1a6d9978f50e)

**Comment by ptc-thesbyro** [comment] 2024-06-14 07:52
Thank you,

I've been able to reproduce your issue using your image. While we identify the cause, you can convert your image to JPG as a workaround.

I'll update this ticket when I have more information.

**Comment by begkonfrank** [comment] 2024-06-14 07:58
thank you

best wishes

**Comment by ptc-thesbyro** [comment] 2024-06-14 09:26
Hello,

We've identified the issue. Your image uses a transparent background, that is, an alpha channel of less than 1. When creating images, make sure to uncheck the Transparency setting in Photoshop or set the colors' alpha channel to 1 in other image editing software.

Due to a bug, the error message for this situation isn't shown when the image fails to meet our format requirements. We expect to have a fix for this soon. 

I recommend having a look at [Troubleshooting the Target Manager](https://developer.vuforia.com/library/getting-started/vuforia-target-manager#troubleshooting-errors-from-the-target-manager), for other image preparations and requirements. 

I will close this ticket once the fix is released.

Hope it helps,

**Comment by begkonfrank** [comment] 2024-06-17 06:40
yes I can upload now

thank you

best wishes

**Comment by ptc-thesbyro** [comment] 2024-06-19 09:49
With the release of 10.24, the Target Manager will now display a Wrong_Color_Model error when trying to add an image with transparent background or alpha channels less than 1. 

I will close this ticket, but feel free to re-open it if the issue persists. 

Thank you,

**Closed by ptc-thesbyro** 2024-06-19 09:49 UTC
Labels: bug-report
