### ISSUE TITLE
App crashes in combination with Vuforia Engine, Area Targets, ARFoundation and "Development Build" enabled in Unity

### ISSUE THREAD

**Issue by PHORIA-Phill** [PTCInc/vuforia-engine#2] opened 2023-02-21 00:26 UTC
**Summary**
A consistent crash occurs when locating an Area Target if the app is built as a 'development build' when using the ARFoundation camera.

**Observed problem**
When the crash occurs, if the build has 'script debugging' enabled and is attached to the profiler, an exception is thrown in the ARAnchorManager script on line 73. It appears to be the standard exception thrown when parts of the Unity API are used when not on the main thread (Screencap of the exception is attached below.) 

From the developer's perspective, the app opens normally and there is no sign of issue. But as soon as the Vuforia engine detects the Area Target the app freezes and crashes to the home screen.

**Expected result**
Application should locate Area Target and continue to run while letting the developer use the standard Unity debugging tools as desired (script debugging, deep profiling, etc)

**Other observations**
- Crash also occurs in the same way on iOS devices with equivalent scene running ARKit.
- This does not happen if using the Vuforia standard camera.

**Reproducible steps**

Project setup
- Create a new Unity project using 2021.3 LTS and the 3D Core template with the Built-in render pipeline.
- Switch to Android platform
- Untick Auto Graphics API & Remove Vulkan from the list. There should only be OpenGLES3 left. _(ARFoundation doesn't support Vulkan)_
- Switch to il2cpp scripting backend
- Switch target architecture to ARM64 and disable ARMv7. _(Google only support 64 bit apps now)_
- Set minimum API level to Android 10 (level 29). _(To remove support for older devices)_
- In XR Plug-in Management enable ARCore under the Android section

Package downloads
- Install ARFoundation 4.2.7
- Download and import the Vuforia Engine 10.13.3 Unity package from here: [https://developer.vuforia.com/downloads/SDK](https://developer.vuforia.com/downloads/SDK)
- Add your licence to the Vuforia configuration

Scene setup
- Remove the original camera from the scene
- Add an ARSession object to the scene (XR > AR Session)
- Add an ARSessionOrigin to the scene (XR > AR Session Origin)
- Add a VuforiaBehaviour to the ‘AR Camera’ Gameobject created under the AR Session Origin
- Add an AreaTarget to the scene (Vuforia Engine > Area Target > Area Target)
- Import a previously generated Area Target into the project by using its Unity package file. _(One that you can test with when built to device)_
- Select the imported area target database in the AreaTargetBehaviour attached to the Area Target Gameobject
- (Optional) Place a cube as a child under the AreaTarget Gameobject in a position that you can see once located. This is just for visual feedback when the area target is successfully detected
- Add the scene to the build
- Confirm the scene is working by building out a non development build.
- Open the app on device and accept the camera permission (you might have to restart the session after accepting)
- You should be able to see the cube placed where you intended under the area target
- Create a second build, this time enable 'development build' (and script debugging if you want to see where the crash occurs)
- As soon as you locate the Area Target using this build, the app will freeze and crash. (😥)

**Affected Vuforia Engine version:**
v10.13.3 and below

**Affected platform:**
 - Windows 10 
 - MacOS
 - Unity 2021.3.18f1 LTS with ARFoundation 4.2.7
 - Unity 2022.2.1f1 with ARFoundation 5.0.3

**Affected device:**
Name: Google Pixel 7 Pro
Model: GE2AE
OS: Android 13

Name: Google Pixel 3a XL
Model: G020B
OS: Android 12

Name: Apple iPhone 12 Pro
Model: MGMK3X/A
OS: iOS 16.3

**Screenshots / Video Recordings**
![exception_screengrab](https://user-images.githubusercontent.com/50894004/220214490-d35eb6b2-f76a-4a1d-9347-ba124fd8beef.png)

**Comment by ptc-pscheper** [comment] 2023-02-21 09:30
Thank you for the elaborated bug report! I'll go through it as soon as possible and try to reproduce the issue based on your reproducible steps. Can you elaborate on where the Area Target is generated and which version of app/generator you used?

**Comment by PHORIA-Phill** [comment] 2023-02-21 10:33
No worries! The Area Target was made using the Area Target Generator app on Windows. I'm 90% sure it was done with version 10.12.3, but if it wasn't that it'll most likely be version 10.9.3.

Cheers!

**Comment by ptc-pscheper** [comment] 2023-02-21 12:22
Thanks for the quick response! Would it be possible to try to regenerate the Area Target in the meantime with the same generator to check if it might be a dataset issue?

**Comment by PHORIA-Phill** [comment] 2023-02-21 22:28
I'm happy to do that for the sake of this bug report, but I can confirm that it has happened to multiple different Area Targets for us. (All generated using the Area Target Generator app)

**Comment by ptc-pscheper** [comment] 2023-02-28 16:24
I've reproduced the issue yesterday and have forwarded it to the R&D team for further investigation. I identified some errors that seem to point to ARCore, but I cannot say for certain why. The current workaround is to not build with "development mode" activated.

**Comment by PHORIA-Phill** [comment] 2023-03-01 00:20
Thanks Patrick! Hopefully the R&D team can get to the bottom of the cause. It's interesting that you're leaning towards ARCore being the culprit at the moment, since I also was about to reproduce the crash on iOS using ARKit. (Let me know whether it would help you if I also provide reproducible steps for iOS too 😄)

**Comment by ptc-pscheper** [comment] 2023-03-02 14:30
Yeah that could very well be. I only reproduced the issue via an Android phone, and since I saw some failure logs which mentioned ARCore, I was leaning to that. I will keep you posted!

**Comment by ptc-pscheper** [comment] 2023-03-22 12:33
This issue will be fixed as part of our **v10.14** release which is scheduled to release today! Thank you for the bug report.

**Closed by ptc-pscheper** 2023-03-22 12:33 UTC
Labels: bug, in progress
