### ISSUE TITLE
White Image from GetCameraImage()

### ISSUE THREAD

**Issue by riccardokhm** [PTCInc/vuforia-engine#143] opened 2024-07-03 14:56 UTC
**Summarize the bug:**
I'm trying to process the frame retrieved from the GetCameraImage method but it always returns a white image. Sometimes it effectively returns the camera frame without augmentation but it seldomly happens.

**Affected Vuforia Engine version:**
v10.24.4

**Affected platform:**
 - Unity
 -  2022.3.20f1

**Affected device:**
 - iPad Pro
 - 6th generation
 - iOs 17.5.1

**Additional comments**
Does the GetCameraImage method work at a predefined resolution?

**Comment by ptc-thesbyro** [comment] 2024-07-04 09:36
Hi, 

Thank you for reaching out. 

Could you try with the sample code provided in [here](https://developer.vuforia.com/library/platform-support/working-camera-unity#access-the-camera-image), and see if that returns images from the camera? And, augmentations are not included in image frames from GetCameraImage(). 

I believe the GetCameraImage() method only returns a predefined resolution, but I will double-check.

**Comment by riccardokhm** [comment] 2024-07-08 14:16
Hi,
thanks for your reply.

Actually, it ended up that I successfully got the camera frame but on Windows, still trying with iOs. Just for the sake of completeness, what kind of geometrical operations do you perform on the frame when we call the GetCameraImage? The image seems somehow scaled and de-zoomed.

Regards,
Riccardo

**Comment by ptc-thesbyro** [comment] 2024-07-09 14:19
If the image seems scaled/zoomed, it could be because the camera image has a different aspect ratio from the screen. But it's difficult to say without some reproducible steps and setup. Let me know if you want us to have a look. 

Hope it helps,

**Comment by ptc-emaggio** [comment] 2024-08-02 08:57
Closing as we do not have sufficient details to reproduce. @riccardokhm I am happy to reopen it when more information becomes available.

**Closed by ptc-emaggio** 2024-08-02 08:57 UTC
Labels: bug-report
