### ISSUE TITLE
Ground Plane doesn't work in Android 

### ISSUE THREAD

**Issue by jenzhou** [PTCInc/vuforia-engine#144] opened 2024-07-18 03:45 UTC
**Summarize the bug:**
Unity 2022.3 and Vuforia 10.24
Ground Plane works on PC, but when it is build in Android, it doesn't work. 

**Observed problem**
There is no build report bug. It is successfully build and installed. But when the app starts in Android, no plane indicator, no hit event, just nothing happened. I have tried ground plane in core sample, but it has compile errors. I have no idea. 

**Expected result**
plane indicator shows, then hit the plane, a sphere disappears.

**Screenshots / Video Recordings**
Share any screenshots or video recordings from the platform or device. You can also use the [Session Recorder]
![无标题](https://github.com/user-attachments/assets/5754af1e-44f9-4104-8172-c5c0b57f56a0)

**Comment by ptc-emaggio** [comment] 2024-07-18 09:30
Hi, please have a look at this troubleshooting guide (https://developer.vuforia.com/library/troubleshooting/troubleshooting-your-app). In particular have a look at the "Check your Device" section. Ground Plane only works on devices where AR Core is supported and endabled.

**Comment by jenzhou** [comment] 2024-07-21 01:24
Thanks. I used VIVO X80. It is not listed on the Vuforia guide your quoted. But it is on the list of AR Core support devices. I also tried the app on O![微信图片_20240721092155](https://github.com/user-attachments/assets/eae8dd21-a349-42cb-aa89-3bda6fb1edf1)

**Comment by ptc-emaggio** [comment] 2024-07-22 07:22
Thanks for the information. Unfortunately we do not have the specific device to reproduce the issue.  Are google services for AR installed on the device (https://play.google.com/store/apps/details?id=com.google.ar.core&hl=en&pli=1)? Without these, or an equivalent OEM deployment (usually done on devices for the Chinese market), ARCore cannot work. One way to be sure ARCore is present and working is to test the Google Hello AR app (see the documentation here https://developers.google.com/ar/develop/java/quickstart  ).

**Comment by ptc-emaggio** [comment] 2024-08-02 08:55
I am closing this issue as we cannot reproduce it on similar class of devices.

**Closed by ptc-emaggio** 2024-08-02 08:55 UTC
Labels: bug-report
