### ISSUE TITLE
ATG:  Validation of the E57 file failed

### ISSUE THREAD

**Issue by Lacreon** [PTCInc/vuforia-engine#20] opened 2023-04-27 14:10 UTC
**Summarize the bug:**
Unable to import E57 file from Leica RTC 360 to ATG.

**Reproducible steps**
1. Make scan with Leica RTC 360
2. Follow Vuforia Scan and Export Instructions for Leica RTC 360: Export with Cyclone REGISTER 360
3. Load e57 to ATG
4. Click on _Import_ or _Generate_
5. Error appears: 
   _E57 processing: Validation of the E57 file failed. Check the validation report for details._
  Failed requirement:
     _'nor:normalX', 'nor:normalY', 'nor:normalZ' fields in PointRecord structure shall be defined or we need to be able to estimate the 
     normals. To estimate normals each Data3D structure shall have associated images from exactly one scanning position through 
     Image2D associatedData3DGuid field._ 
6. Export E57 again but with Cyclone CORE and ticked options: 
  ![image](https://user-images.githubusercontent.com/58328479/234886351-3e27b223-4c61-436e-a45b-bcbf9e8b4fd0.png)
7. Load e57 to ATG
8. Click on _Import_ or _Generate_
5. Error appears: 
     _E57 processing: Validation of the E57 file failed. Check the validation report for details._
  Failed requirement:
     _E57 shall contain one or more Image2D structures that have either 'sphericalRepresentation' field or 'pinholeRepresentation' field._ 

**Affected ATG**
v10.15.3.

**Affected platform:**
Windows

**Device or platform logs**
 [ SUCCESS ] E57 shall contain one or more Data3D structures. 

 [ SUCCESS ] 'cartesianBounds' field in Data3D structure shall be defined. 

 [ SUCCESS ] 'colorLimits' field in Data3D structure shall be defined with color minimum < color maximum for all channels. 

 [ SUCCESS ] 'cartesianX', 'cartesianY', 'cartesianZ' fields in PointRecord structure shall be defined. 

 [ SUCCESS ] 'colorRed', 'colorGreen', 'colorBlue' fields in PointRecord structure shall be defined. 

 [ SUCCESS ] 'nor:normalX', 'nor:normalY', 'nor:normalZ' fields in PointRecord structure shall be defined or we need to be able to estimate the normals. To estimate normals each Data3D structure shall have associated images from exactly one scanning position through Image2D associatedData3DGuid field. 

 [ SUCCESS ] 'isColorInvalid' field in PointRecord structure must not be defined. 

 [   FAIL  ] E57 shall contain one or more Image2D structures that have either 'sphericalRepresentation' field or 'pinholeRepresentation' field. 

 [ SUCCESS ] 'pose' field in Image2D structure shall be defined. 

 [ SUCCESS ] Spherical images shall have minimal resolution of 4096x2048 and their width = 2 * height. 

 [ SUCCESS ] Pinhole images shall have minimal resolution of 1024x1024. 

 
 E57 processing: Validation of the E57 file failed. Check the validation report for details.

**Workaround**
None

**Comment by ptc-ddowning** [comment] 2023-04-27 14:34
Hello,

Is this a regression? Did you have previous success with an earlier version of the ATG?

Thanks.

**Comment by ptc-ddowning** [comment] 2023-04-27 15:05
Hello,

Overall, it is very important that you follow the steps **exactly** as [documented](https://library.vuforia.com/area-targets/leica-scans#transferring-and-post-processing-the-scan). I know that you included that you did in step #2, but it is important to understand that the Leica software is complex so any change in the workflow steps can result in a failed import. 

We believe that REGISTER 360 may have added an option to unify pointclouds - be sure to unselect that for the export .

Additionally, the logging information indicates that the individual scans were merged/unified after alignment, and exported as one 'unstructured' scan. Since REGISTER 360 didn't add the normals, the ATG cannot re-create them. If you export the scan without merging them, the ATG has an internal ability to create the normals.

Lastly, the use of Cyclone Core is not recommended so please only work with REGISTER 360.

If you believe you've resolved all of the issues above, have followed our documentation exactly and the import still fails, please provide the detailed steps and settings from the REGISTER 360 export so that we can review them further.

Thank you.

**Comment by ptc-ddowning** [comment] 2023-04-28 14:35
Hello,

We believe this could be a new option that needs to be unchecked during export:
https://rcdocs.leica-geosystems.com/cyclone-register-360/latest/option-to-create-single-point-cloud-when-creating-


[We currently recommended a similar option](https://library.vuforia.com/area-targets/leica-scans#transferring-and-post-processing-the-scan) `Create point cloud during finalized registration creation` to be checked, but this may work differently in newer REGISTER 360 versions.

Thank you.

**Comment by ptc-pscheper** [comment] 2023-05-04 21:20
@Lacreon Was the feedback from Dave good enough to support you in creating a successful Area Target?

**Comment by Lacreon** [comment] 2023-05-05 07:59
Hello,

unfortunately, the steps described above didn't work for me. However, I have sent Dave a step-by-step video of my export process via email. I will post an update as soon as there is something new.

Thank you.

**Comment by bbiaudet** [comment] 2023-05-15 10:23
Hello, I also have a problem importing a leica RTC360 scan, like you, I followed the vuforia doc but on the other hand I do not encounter the same error as you.

**Affected ATG**
v10.15.3.

**Affected platform:**
Windows / Mac

**Device or platform logs**
[ SUCCESS ] E57 shall contain one or more Data3D structures.
[ SUCCESS ] 'cartesianBounds' field in Data3D structure shall be defined.
[ SUCCESS ] 'colorLimits' field in Data3D structure shall be defined with color minimum < color maximum for all channels.
[ SUCCESS ] 'cartesianX', 'cartesianY', 'cartesianZ' fields in PointRecord structure shall be defined.
[ SUCCESS ] 'colorRed', 'colorGreen', 'colorBlue' fields in PointRecord structure shall be defined.
[ FAIL ] 'nor:normalX', 'nor:normalY', 'nor:normalZ' fields in PointRecord structure shall be defined or we need to be able to estimate the normals. To estimate normals each Data3D structure shall have associated images from exactly one scanning position through Image2D associatedData3DGuid field.
[ SUCCESS ] 'isColorInvalid' field in PointRecord structure must not be defined.
[ SUCCESS ] E57 shall contain one or more Image2D structures that have either 'sphericalRepresentation' field or 'pinholeRepresentation' field.
[ SUCCESS ] 'pose' field in Image2D structure shall be defined.
[ SUCCESS ] Spherical images shall have minimal resolution of 4096x2048 and their width = 2 * height.
[ SUCCESS ] Pinhole images shall have minimal resolution of 1024x1024.

**Comment by Lacreon** [comment] 2023-05-17 12:01
Hello bbiaudet,

it is the same error. 

Export with Cyclone REGISTER 360 gives me: 

[ FAIL ] 'nor:normalX', 'nor:normalY', 'nor:normalZ' fields in PointRecord structure shall be defined or we need to be able to estimate the normals. To estimate normals each Data3D structure shall have associated images from exactly one scanning position through Image2D associatedData3DGuid field.

 Export with Cyclone CORE gives me: 

[ FAIL ] E57 shall contain one or more Image2D structures that have either 'sphericalRepresentation' field or 'pinholeRepresentation' field.

Cyclone REGISTER 360 version:  2022.0.1

**Comment by bbiaudet** [comment] 2023-05-17 12:19
Hello Lacreon,

I managed to load another scan into ATG, the first scan was with an exterior view and the second the interior of a church. So I wonder if ATG does not need a "ceiling" to generate the mapping?

**Comment by ptc-ddowning** [comment] 2023-05-17 12:39
Hello @bbiaudet - This should not be the case. The scan should be agnostic towards having the ceiling as part of the scanning data. However, I will provide your recent feedback to the team.

@Lacreon & @bbiaudet - We are working to get an updated license for the latest REGISTER versions and will update our documentation accordingly. I will post an update with any immediate findings to unblock you here.

Thank you for your patience and understanding.

**Comment by ptc-ddowning** [comment] 2023-05-17 13:18
@bbiaudet as we are working with a 3rd party tool, i.e REGISTER, it is most helpful to provide a detailed description of both the steps taken _in addition to the_ error messages from the ATG, similar to @Lacreon's [original post](https://github.com/PTCInc/vuforia-engine/issues/20#issue-1686947609). Otherwise, we will only be guessing as to the possible source of the issue.

**Comment by ptc-ddowning** [comment] 2023-05-18 13:16
@bbiaudet thank you for the confirmation as it is helpful.

If the team needs it, would you be willing to share the scan that failed import?

**Comment by bbiaudet** [comment] 2023-05-18 13:46
Yes no problem

**Comment by bbiaudet** [comment] 2023-05-31 06:34
Hello everyone,

we redid tests on our side with the RTC360 with the following workflow:

**Trial 1**
- One room scan with 1 station
- Processing in Cyclone Register 360 by following the vuforia doc step by step (https://library.vuforia.com/area-targets/leica-scans)
- Import into ATG
- Successful import

**Trial 2**
- One room scan with 2 station
- Processing in Cyclone Register 360 by following the vuforia doc step by step (https://library.vuforia.com/area-targets/leica-scans)
- Import into ATG
- Import in error with the following error : [ FAIL ] 'nor:normalX', 'nor:normalY', 'nor:normalZ' fields in PointRecord structure shall be defined or we need to be able to estimate the normals. To estimate normals each Data3D structure shall have associated images from exactly one scanning position through Image2D associatedData3DGuid field.

We asked leica if there was a difference between the point clouds by transferring the files to them, and they said no.

The files are available if you want to test on your side.

Good day to you

**Comment by ptc-ddowning** [comment] 2023-07-20 18:33
Closing due to lack of response. Feel free to reopen if required.

**Closed by ptc-ddowning** 2023-07-20 18:33 UTC
Labels: bug, in progress
