### ISSUE TITLE
[MTG] Export AMT database error

### ISSUE THREAD

**Issue by BlackRandomCraft** [PTCInc/vuforia-engine#65] opened 2023-10-12 16:11 UTC
**Summarize the bug:**
When using Vuforia Model Target Generator without admin rights on a Windows 10 (build 1903) computer, an error occurs when exporting the AMT database and there is no export.

**Observed problem**
-

**Expected result**
The model should be exported to the selected folder

**Other observations**
-

**Reproducible steps**
1. Open Model Target Generator without admin privileges on Windows PC
2. Go to AMT Database
3. Export model
4. Select folder
5. See error

**Affected Vuforia Model Target Generation version:**
v10.17.4

**Affected platform:**
 - Workstation OS: Windows 10, 1903

**Screenshots / Video Recordings**
![image](https://github.com/PTCInc/vuforia-engine/assets/67829038/3c937a57-966f-43f5-829f-41b6973fdc37)

**Workaround**
No

**Additional comments**
-

**Comment by ptc-ddowning** [comment] 2023-10-12 16:48
Hello @BlackRandomCraft,

Since you are not an admin user, are you trying to export to a location where your account has write permissions?

Thanks,
Vuforia Engine Support

**Comment by BlackRandomCraft** [comment] 2023-10-12 16:50
yes, in c:\users\(user)\documents

**Comment by BlackRandomCraft** [comment] 2023-10-13 14:17
1. 
![image](https://github.com/PTCInc/vuforia-engine/assets/67829038/e52be980-2419-44b6-abac-4891dad19631)
2-4. same error

**Comment by ptc-ddowning** [comment] 2023-10-16 18:05
Hello,

Unfortunately, we've been unable to replicate your failure. We attempted the same steps as [mentioned above](https://github.com/PTCInc/vuforia-engine/issues/65#issuecomment-1760128329).

If you have any additional insights to share for replicating, please let us know.

Thanks,
Vuforia Engine Support

**Comment by ptc-ddowning** [comment] 2023-10-31 18:55
Closing due to inability to reproduce. Feel free to re-open if additional information becomes available.

Thanks, 
Vuforia Engine Support

**Closed by ptc-ddowning** 2023-10-31 18:55 UTC
Labels: bug
