### ISSUE TITLE
The camera is only showing a black screen on some devices.

### ISSUE THREAD

**Issue by JoeWATANABE1101** [PTCInc/vuforia-engine#169] opened 2024-12-10 07:21 UTC
**Summarize the bug:**
The camera is only showing a black screen on some devices.
Ver 10.15 is available but not available higher version than ver 10.22.

**Observed problem**
According to the logs, Vuforia initialization has successful.

**Expected result**
Displaying a camera view.

**Reproducible steps**
1. Create a simple unity project that has a scene include ARCamera and ModelTarget.
  Unity 2022.3.30 (URP) / Vuforia higher than ver 10.22 
  Not install ARCore
1. Build for Android
1. Launch on Android device.

**Affected Vuforia Engine version:**
v10.22.

**Affected platform:**
 - Workstation OS:Android 10
 - Platform Unity
 - Platform version 2022.3.30

**Affected device:**
- HUAWEI P30Lite (Android9, 10)
- HUAWEI nova lite 3 (Android10)
- ASUS ZenFone 5(Android8)

**Screenshots / Video Recordings**
Share any screenshots or video recordings from the platform or device. You can also use the [Session Recorder](https://library.vuforia.com/platform-support/recording-and-playback).

**Device or platform logs**
[2024_06_20_15_05_27.txt](https://github.com/user-attachments/files/18074715/2024_06_20_15_05_27.txt)

**Comment by ptc-thesbyro** [comment] 2024-12-10 13:04
Hi, 

Thank you for your report. 

This may be related to a similar black screen issue reported here #149 

We are still investigating the cause of this and working on a workaround and fix. I will let you know when we know more.

**Comment by Archi97** [comment] 2024-12-21 10:51
@ptc-thesbyro seems it is.  i have posted new details, hope it will help somehow.

**Comment by ptc-emaggio** [comment] 2024-12-23 09:23
I will close this issue as it is a duplicate of https://github.com/PTCInc/vuforia-engine/issues/149

**Closed as not planned by ptc-emaggio** 2024-12-23 09:23 UTC
Labels: bug-report
