### ISSUE TITLE
Area Target Test App not working on HoloLens 2

### ISSUE THREAD

**Issue by travis-rothbloom** [PTCInc/vuforia-engine#3] opened 2023-02-21 22:25 UTC
**Summarize the bug:**
I'm unable to get any Area Target app working on my HoloLens 2, whose system updates are current. 

**Observed problem**
When I try to get the Area Targets Test App to work using the guide below, I'm able to build the app, deploy to the HL2, run it initially to create the dataset folders, and then upload my area targets (just the .dat, .xml, and occlusion .3dt files) into the folder using the Device Portal. When I then go to run the app again on the HL2, I do successfully see that the two datasets are registered.

When I go to activate a dataset, however, the loading revolving circle (Loading Scene) does start but then seems to freeze; considering that the animation of this loading circle is supposed to keep going in the Update method, it seems like nothing is happening at all. I've let this go on for 20 minutes and no change to the stuck loading circle, and the dot next to the dataset does not turn green. These scans are not very large (one is <2k sqft, the other maybe closer to 5k). All the other voice commands seem to work.

**Expected result**
I'd expect the app to not hang up during loading of the dataset, and then to properly locate the area target occlusion outline onto the real area.

**Other observations**
Share any other observations that you made while experiencing the bug.

**Reproducible steps**
1. Complete steps 1 through 5 in the "Installing and Testing on HoloLens" section at this link: https://library.vuforia.com/develop-area-targets/area-targets-test-app-user-guide#installing-and-testing-on-hololens
2. After step 5, at the instruction to "Start the app from the HoloLens' menu", any datasets loaded into the HoloLens LocalState folder should appear in the list with grey circles next to them. 
3. Say "Activate dataset 1" should then bring up the loading animation, but the animation will be frozen and the app will not proceed further.

**Affected Vuforia Engine version:**
v10.12.3, both Vuforia and the ATG

**Affected platform:**
 - Workstation OS: Windows
 - Platform: Unity
 - Platform version 2021.3.4f1
 - Area Tag Capture Device: Matterport Pro 2

**Affected device:**
 - Name: HoloLens
 - Model: 2
 - OS: 22H1 - 20348.1537

**Screenshots / Video Recordings**
[_**Image of hangup**_](https://community.vuforia.com/sites/default/files/attachments/20230120_085523_HoloLens.jpg)

**Affected database**
N/A, this is a private Area Tag

**Device or platform logs**
I could not find any logs created by the app on the device. I tried to run this in debug mode from VS but because of the requirement to place the dataset files onto the HL after the app is first deployed, this wouldn't work as every time I started debug mode, it cleared those folders' contents.

**Workaround**
No

**Additional comments**
I've been corresponding with Patrick Scheper offline and through [**_this forums thread_**](https://community.vuforia.com/node/4894492), he asked me to officially log this as he was able to reproduce the issue on his end with any Area Target, implying that the issue is with the app itself.

**Comment by ptc-pscheper** [comment] 2023-02-22 16:32
@travis-rothbloom can you verify that a license key has been added to the Vuforia Configuration file? Once the key has been added the loading circle should not get stuck. This was my personal mistake trying to reproduce the issue you mentioned on the forums.

![Unity_YuWcHTYxgF](https://user-images.githubusercontent.com/88328882/220693176-40498a67-582a-4a19-aff5-8e1180eac1ab.gif)

**Comment by travis-rothbloom** [comment] 2023-02-22 23:34
Hi Patrick, I can confirm I added the license key in there before deploying.

**Comment by cheles** [comment] 2023-02-23 11:58
From your file, DllNotFoundException: Unable to load DLL 'VuforiaEngine.dll': The specified module could not be found.
  at Vuforia.VuEngineConfigSet.Create () [0x00000] in <00000000000000000000000000000000>:0 
  at Vuforia.Internal.NativeBridge.NativeEngineConfigSet..ctor (Vuforia.VuforiaConfiguration vuforiaConfiguration) [0x00000] in <00000000000000000000000000000000>:0 
  at Vuforia.Internal.NativeBridge.NativeEngineConfigSet..ctor (Vuforia.VuforiaConfiguration vuforiaConfiguration, System.String recordingPath) [0x00000] in <00000000000000000000000000000000>:0 
  at Vuforia.Internal.NativeBridge.NativeEngineFactory.CreateEngineConfig (Vuforia.VuforiaConfiguration vuforiaConfiguration, System.String recordingPath) [0x00000] in <00000000000000000000000000000000>:0 
  at Vuforia.Internal.Core.Engine.Init (System.String recordingPath) [0x00000] in <00000000000000000000000000000000>:0 
  at Vuforia.VuforiaApplication.Initialize () [0x00000] in <00000000000000000000000000000000>:0 
  at Vuforia.Internal.Core.OneTimeInitialization.Initialize () [0x00000] in <00000000000000000000000000000000>:0 

I don't think that you've added the vuforia engine package correctly or it's missing entirely from the project. that might happen because its >100MB and github has a limit < 100MB files.

**Comment by ptc-pscheper** [comment] 2023-02-23 14:43
Thanks a lot @cheles. I agree that this seems to be the cause of the issue. My recommendation would be to reimport the test app .unitypackage, but a new fresh project might be better.

**Comment by ptc-pscheper** [comment] 2023-02-28 15:05
I closed this issue for now, but feel free to re-open the issue if needed. Thank you!

**Closed** 2023-02-28 15:04 UTC
Labels: bug

**Comment by travis-rothbloom** [comment] 2023-03-06 19:50
Thanks @ptc-pscheper, I can confirm it's working now. I do believe it's the newer version of Vuforia but either that and/or reimporting seemed to solve the issue.
