### ISSUE TITLE
Failed to create ModelTargetObserver: DATABASE_LOAD_ERROR

### ISSUE THREAD

**Issue by lbfff** [PTCInc/vuforia-engine#128] opened 2024-06-11 05:58 UTC
**Summarize the bug:**
Custom MTG DB cannot load on UnityEdotor(2020.3.18f1 and 2023.2.20f1c1)

**Observed problem**
My Vuforia license is basic.
I created a new Database using MTG(10.22.5) with 1 obj to test Model Target feature.
I used the CoreSample project with Vuforia Engine and I applied my custom DB in the inspector window with the Sample Scene for Model Target.
Once I clicked play, Console shows the load error message:Exception in callback: Failed to create ModelTargetObserver: DATABASE_LOAD_ERROR.

**Expected result**
Creating dataset and Vuforia Started.

**Other observations**
1.When I saw this bug report(https://github.com/PTCInc/vuforia-engine/issues/69), I tried to change my password or even account to regenerate the DB and license, but it still didn't work.
2.I also created a new Database using MTG(10.22.5) with another fbx file to generate Database, but it still didn't work.

**Reproducible steps**
1. Install MGT(10.22.5) on Windows
2. Log in with basic license account
3. Click Create button to get Custom DB using obj files.
4. Import the DB in CoreSample unity project.
5. Open ModelTargetStandrad Scene which import by Core Samples,Switch Database to my custom DB.
6. Click Play.
7. See Error.

**Affected Vuforia Engine version:**
v10.22.5.

**Affected platform:**
 - Workstation OS: Windows
 - Platform : Unity
 - Platform version :2020.3.18f1,2023.2.20f1c1

**Device or platform logs**
Exception in callback: Failed to create ModelTargetObserver: DATABASE_LOAD_ERROR.
UnityEngine.Debug:LogErrorFormat (string,object[])
Vuforia.Internal.Utility.UnityLogger:LogError (string,object[])
Vuforia.Internal.Utility.Log:Error (string,object[])
Vuforia.Utility.ExtensionMethods.DelegateHelper:InvokeDelegate (System.Delegate,object[])
Vuforia.Utility.ExtensionMethods.DelegateHelper:InvokeWithExceptionHandling (System.Action)
Vuforia.Internal.Core.Engine:OnStart ()
Vuforia.Internal.Core.Engine:Start (System.Action)
Vuforia.Internal.Core.Engine:Start ()
Vuforia.VuforiaBehaviour:AfterVuforiaInitialized (Vuforia.VuforiaInitError)
System.Delegate:DynamicInvoke (object[])
Vuforia.Utility.ExtensionMethods.DelegateHelper:InvokeDelegate (System.Delegate,object[])
Vuforia.Utility.ExtensionMethods.DelegateHelper:InvokeWithExceptionHandling<Vuforia.VuforiaInitError> (System.Action`1<Vuforia.VuforiaInitError>,Vuforia.VuforiaInitError)
Vuforia.Internal.Core.Engine:InitOnCameraReady ()
Vuforia.WebCam:HandleFirstWebCamFrame ()
Vuforia.WebCam:<Init>b__34_0 (bool)
Vuforia.Internal.Utility.VuforiaCoroutineUtility/<RunCoroutineWithTimeout>d__1:MoveNext ()
UnityEngine.SetupCoroutine:InvokeMoveNext (System.Collections.IEnumerator,intptr)

**Comment by ptc-epassaro** [comment] 2024-06-11 07:59
Hi @lbfff, did you add your license key to the VuforiaConfiguration? Here you can find the steps on how to configure a Unity project with Vuforia: https://developer.vuforia.com/library/getting-started/getting-started-vuforia-engine-unity#vuforia-engine-setup

**Comment by lbfff** [comment] 2024-06-11 08:06
> Hi @lbfff, did you add your license key to the VuforiaConfiguration? Here you can find the steps on how to configure a Unity project with Vuforia: https://developer.vuforia.com/library/getting-started/getting-started-vuforia-engine-unity#vuforia-engine-setup

Yes, I added my license key to the VuforiaConfiguration but it still didn't work.
![4](https://github.com/PTCInc/vuforia-engine/assets/172341558/4b7d0d43-e52a-40a5-b004-e23a292730ea)

**Comment by ptc-epassaro** [comment] 2024-06-11 11:10
@lbfff Does the VuforiaMars_ModelTarget work or does it give you the same error?

**Comment by ptc-epassaro** [comment] 2024-06-11 13:42
@lbfff if possible, it would be great if you could share your ModelTarget databases with us so we can try to reproduce the issue. You can share it with us via vuforia-feedback@ptc.com

**Comment by lbfff** [comment] 2024-06-11 14:00
> @lbfff if possible, it would be great if you could share your ModelTarget databases with us so we can try to reproduce the issue. You can share it with us via [vuforia-feedback@ptc.com](mailto:vuforia-feedback@ptc.com)

I just replied to you in the email and uploaded my DB in the attachment. Did you not receive it？

**Comment by ptc-epassaro** [comment] 2024-06-12 11:02
Hi @lbfff, unfortunately we still haven't received your email with the dataset. Could you please retry?

**Comment by lbfff** [comment] 2024-06-12 14:44
> @lbfff if possible, it would be great if you could share your ModelTarget databases with us so we can try to reproduce the issue. You can share it with us via [vuforia-feedback@ptc.com](mailto:vuforia-feedback@ptc.com)
I have sent a new email to this email, have you received it？

**Comment by lbfff** [comment] 2024-06-12 14:46
> @lbfff if possible, it would be great if you could share your ModelTarget databases with us so we can try to reproduce the issue. You can share it with us via [vuforia-feedback@ptc.com](mailto:vuforia-feedback@ptc.com)

I have sent a new email with attachments to this email. Have you received it？

**Comment by ptc-epassaro** [comment] 2024-06-12 15:43
@lbfff yes, thank you!
I was able to reproduce the issue with your database. We will investigate the issue and keep you posted on the progress.

**Comment by lbfff** [comment] 2024-06-28 15:27
> @lbfff yes, thank you! I was able to reproduce the issue with your database. We will investigate the issue and keep you posted on the progress.

May I ask when this issue can be fixed? I really hope to use Vuforia to provide our team with a verifiable model tracking solution as soon as possible.

**Comment by ptc-epassaro** [comment] 2024-07-01 09:59
Hi @lbfff, a fix that could potentially be related to this issue has been released with Vuforia 10.24, sorry for not getting back to you right away. Could you please try the new version of the Model Target Generator and let us know if things improve?

**Comment by lbfff** [comment] 2024-07-02 05:34
> Hi @lbfff, a fix that could potentially be related to this issue has been released with Vuforia 10.24, sorry for not getting back to you right away. Could you please try the new version of the Model Target Generator and let us know if things improve?

I downloaded the latest MTG(10.24.4), but in the last step, clicking on Generate Standard ModelTarget failed to generate an error message in the pop-up window. The reason for the error is Invalid signature received. 
![2001](https://github.com/PTCInc/vuforia-engine/assets/172341558/1776c53e-2a6c-4d5a-9cc9-e5665146fecd)

**Comment by ptc-epassaro** [comment] 2024-07-02 07:50
Thank you for trying the new version. I will talk to the team and let you know as soon as I have more information.

**Comment by ptc-epassaro** [comment] 2024-07-02 08:19
@lbfff could you please send us the log file from the Model Target Generator that is produced when this error happens?
You can follow these steps to reach the file:
- Try to create a ModelTarget to get the error in the app
- Go back to the Home screen of the Model Target Generator
- Click on your initials in the upper-right corner
- Click the `Open Log` option
- You should see the log file in an Explorer window

If you prefer, you can also share the file with us by sending it via email to vuforia-feedback@ptc.com.

**Comment by ptc-epassaro** [comment] 2024-09-17 07:14
Closing this issue due to inactivity. Feel free to reopen it if the problem persists.

**Closed by ptc-epassaro** 2024-09-17 07:14 UTC
Labels: bug-report
